    name: Deploy Frontend NextJS

    on:
      push:
        branches:
          - main # Or your production branch

    jobs:
      deploy:
        runs-on: ubuntu-24.04

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Node.js
            uses: actions/setup-node@v4
            with:
              node-version: '18.19.1' # Or your desired Node.js version

          - name: Install dependencies
            run: npm install

          - name: Build Next.js application
            run: npm run build # Or npm run build && npm run export for static export

          - name: Deploy to Server
            uses: appleboy/ssh-action@master
            with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USERNAME }}
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              script: |
                # Example commands for deploying and restarting a Next.js app
                # Adjust based on your server setup (e.g., PM2, Nginx)
                cd /var/www/html/aceofspace
                rm -rf .next # Or out for static export
                mkdir -p .next # Or out
                # Copy build output from GitHub Actions workspace to server
                scp -r .next/* root@host:/var/www/html/aceofspace/.next/
                # If using a Next.js server
                pm2 restart aceofspace # Example using PM2
                # If using static export with Nginx, update Nginx config and reload
                # sudo systemctl reload nginx
